#!/bin/bash

export QHOME=C:\Users\dmorgan1\AppData\Local\Continuum\anaconda3\envs\jupyterenv\q

$QHOME/l64/q hpopt_compare.q -q -fin ... -fout ... -dtype ... -targ ...
$QHOME/l64/q hpopt_compare.q -q -fin ... -fout ... -dtype ... -targ ...
$QHOME/l64/q hpopt_compare.q -q -fin ... -fout ... -dtype ... -targ ...